import javax.swing.ImageIcon;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohit Vaishnav
 */import java.sql.*;
 import javax.swing.*;
 
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
         setSize(569,320);
         
                        
         
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jDialog3 = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jDialog4 = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jDialog5 = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jDialog6 = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jDialog7 = new javax.swing.JDialog();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jDialog8 = new javax.swing.JDialog();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jButton10 = new javax.swing.JButton();
        jDialog9 = new javax.swing.JDialog();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jButton11 = new javax.swing.JButton();
        jDialog10 = new javax.swing.JDialog();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jButton12 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jDialog1.setMinimumSize(new java.awt.Dimension(400, 300));
        jDialog1.getContentPane().setLayout(null);

        jScrollPane1.setEnabled(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\nMinimum Requirements\n\n    OS: Win Xp 32\n    Processor: Intel Core 2 Duo E4600 2.4GHz / AMD Athlon 64 X2 Dual Core 4800+\n    Graphics: AMD Radeon HD 3600 Series or NVIDIA GeForce GT 330\n    System Memory: 1 GB RAM\n    Storage: 15 GB Hard drive space\n    DirectX 9 Compatible Graphics Card\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        jDialog1.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 30, 330, 180);

        jButton3.setText("Ok");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton3);
        jButton3.setBounds(160, 220, 73, 23);

        jDialog2.setMinimumSize(new java.awt.Dimension(400, 300));
        jDialog2.getContentPane().setLayout(null);

        jScrollPane2.setEnabled(false);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("\nMinimum Requirements\n\n    OS: Win Xp 32\n    Processor: Intel Core 2 Duo E6600 2.4GHz / AMD Athlon 64 X2 Dual Core 5600+\n    Graphics: AMD Radeon HD 5670 512MB or NVIDIA GeForce 8800 GT\n    System Memory: 1 GB RAM\n    Storage: 2 GB Hard drive space\n    DirectX 9 Compatible Graphics Card\n\n\n");
        jScrollPane2.setViewportView(jTextArea2);

        jDialog2.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 30, 350, 180);

        jButton4.setText("Ok");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton4);
        jButton4.setBounds(160, 220, 73, 23);

        jDialog3.setMinimumSize(new java.awt.Dimension(400, 300));
        jDialog3.getContentPane().setLayout(null);

        jScrollPane3.setEnabled(false);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("\nMinimum Requirements\n\n    OS: Win Xp 32\n    Processor: Intel Core 2 Duo E4600 2.4GHz / AMD Athlon 64 X2 Dual Core 4800+\n    Graphics: AMD Radeon HD 3600 Series or NVIDIA GeForce GT 330\n    System Memory: 1 GB RAM\n    Storage: 10 GB Hard drive space\n    DirectX 9 Compatible Graphics Card\n\n");
        jScrollPane3.setViewportView(jTextArea3);

        jDialog3.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(30, 30, 330, 180);

        jButton5.setText("Ok");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jButton5);
        jButton5.setBounds(160, 220, 73, 23);

        jDialog4.setMinimumSize(new java.awt.Dimension(400, 300));
        jDialog4.getContentPane().setLayout(null);

        jScrollPane4.setEnabled(false);

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("\nMinimum Requirements\n\n    OS: Win Xp 32\n    Processor: Intel Core 2 Duo E4600 2.4GHz / AMD Athlon 64 X2 Dual Core 4800+\n    Graphics: AMD Radeon HD 3600 Series or NVIDIA GeForce GT 330\n    System Memory: 1 GB RAM\n    Storage: 15 GB Hard drive space\n    DirectX 9 Compatible Graphics Card\n\n");
        jScrollPane4.setViewportView(jTextArea4);

        jDialog4.getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(30, 30, 330, 180);

        jButton6.setText("Ok");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jDialog4.getContentPane().add(jButton6);
        jButton6.setBounds(160, 220, 73, 23);

        jDialog5.setMinimumSize(new java.awt.Dimension(400, 300));
        jDialog5.getContentPane().setLayout(null);

        jScrollPane5.setEnabled(false);

        jTextArea5.setEditable(false);
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText("\nMinimum Requirements\n\n    OS: Win Xp 32\n    Processor:Intel or AMD 1.5 GHz supporting SSE2 instructions\n    System Memory: 1 GB RAM\n    Storage: 15 GB Hard drive space\n    DirectX 9 Compatible Graphics Card\n\n");
        jScrollPane5.setViewportView(jTextArea5);

        jDialog5.getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(30, 30, 330, 180);

        jButton7.setText("Ok");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jDialog5.getContentPane().add(jButton7);
        jButton7.setBounds(160, 220, 73, 23);

        jDialog6.setMinimumSize(new java.awt.Dimension(400, 300));
        jDialog6.getContentPane().setLayout(null);

        jScrollPane6.setEnabled(false);

        jTextArea6.setEditable(false);
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea6.setRows(5);
        jTextArea6.setText("\nMinimum Requirements\n    \n    OS: Windows 7 SP1, Windows 8.1, Windows 10 (64-bit versions only)\n    Processor: AMD FX 6300 @ 3.8 GHz, Intel Core i5 2400 @ 3.1 GHz, Ryzen 3 - 1200\n    Video: AMD Radeon R9 285 (2GB VRAM with Shader Model 5.0) or NVIDIA GeForce GTX 660\n    Memory: 8GB RAM\n    Resolution: 720p\n    Targeted framerate: 30 FPS\n    Video Preset: Low\n    Storage: 46GB available hard drive space\n    DirectX: DirectX June 2010 Redistributable\n    Sound: DirectX 9.0c compatible sound card with latest drivers\n\n");
        jScrollPane6.setViewportView(jTextArea6);

        jDialog6.getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(30, 30, 330, 180);

        jButton8.setText("Ok");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jDialog6.getContentPane().add(jButton8);
        jButton8.setBounds(160, 220, 73, 23);

        jDialog7.setMinimumSize(new java.awt.Dimension(400, 300));
        jDialog7.getContentPane().setLayout(null);

        jScrollPane7.setEnabled(false);

        jTextArea7.setEditable(false);
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea7.setRows(5);
        jTextArea7.setText("\nMinimum Requirements\n\n \n\n    OS: Windows 7 SP1, Windows 8.1, Windows 10 (64-bit versions only)\n    PROCESSOR: Intel Core i5-2400s @ 2.5 GHz or AMD FX-6350 @ 3.9 GHz or equivalent\n    VIDEO CARD: NVIDIA GeForce GTX 660 or AMD R9 270 \n    SYSTEM RAM: 6GB\n    Resolution: 720p\n    Video Preset: Lowest\n\n");
        jScrollPane7.setViewportView(jTextArea7);

        jDialog7.getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(30, 30, 330, 180);

        jButton9.setText("Ok");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jDialog7.getContentPane().add(jButton9);
        jButton9.setBounds(160, 220, 73, 23);

        jDialog8.setMinimumSize(new java.awt.Dimension(400, 300));
        jDialog8.getContentPane().setLayout(null);

        jScrollPane8.setEnabled(false);

        jTextArea8.setEditable(false);
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea8.setRows(5);
        jTextArea8.setText("\nMinimum Requirements\n\n    Core i7-3770 4-Core 3.4GHz\n    FX-9590\n    GEFORCE GTX 1060 6GB\n    RADEON RX 480 8GB\n    8 GB\n\n");
        jScrollPane8.setViewportView(jTextArea8);

        jDialog8.getContentPane().add(jScrollPane8);
        jScrollPane8.setBounds(30, 30, 330, 180);

        jButton10.setText("Ok");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jDialog8.getContentPane().add(jButton10);
        jButton10.setBounds(160, 220, 73, 23);

        jDialog9.setMinimumSize(new java.awt.Dimension(400, 300));
        jDialog9.getContentPane().setLayout(null);

        jScrollPane9.setEnabled(false);

        jTextArea9.setEditable(false);
        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea9.setRows(5);
        jTextArea9.setText("\nMinimum Requirements\n\n    OS: Win Xp 32\n    Processor: Intel Core 2 Duo E4600 2.4GHz / AMD Athlon 64 X2 Dual Core 4800+\n    Graphics: AMD Radeon HD 3600 Series or NVIDIA GeForce GT 330\n    System Memory: 1 GB RAM\n    Storage: 15 GB Hard drive space\n    DirectX 9 Compatible Graphics Card\n\n");
        jScrollPane9.setViewportView(jTextArea9);

        jDialog9.getContentPane().add(jScrollPane9);
        jScrollPane9.setBounds(30, 30, 330, 180);

        jButton11.setText("Ok");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jDialog9.getContentPane().add(jButton11);
        jButton11.setBounds(160, 220, 73, 23);

        jDialog10.setMinimumSize(new java.awt.Dimension(400, 300));
        jDialog10.getContentPane().setLayout(null);

        jScrollPane10.setEnabled(false);

        jTextArea10.setEditable(false);
        jTextArea10.setColumns(20);
        jTextArea10.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea10.setRows(5);
        jTextArea10.setText("\nMinimum Requirements\n\nOS: Windows 7 SP1, Windows 8.1, Windows 10 (64-bit versions only)\nPROCESSOR: Intel Core i5-2400 @ 3.1 GHz or AMD FX-6300 @ 3.5 GHz or equivalent\nVIDEO CARD: NVIDIA GeForce GTX 670 or AMD R9 270 (2GB VRAM with Shader Model 5.0 or better)\nSYSTEM RAM: 8GB\nResolution: 720p\nVideo Preset: Low\n");
        jScrollPane10.setViewportView(jTextArea10);

        jDialog10.getContentPane().add(jScrollPane10);
        jScrollPane10.setBounds(30, 30, 330, 180);

        jButton12.setText("Ok");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jDialog10.getContentPane().add(jButton12);
        jButton12.setBounds(160, 220, 73, 23);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jComboBox1.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Castlevania Lords Of Shadow", "Castlevania Mirror Of Fates", "Castlevania Lords Of Shadow 2", "Shadow Of Colossus", "Sphinx And The Cused Mummy", "Assassins Creed Odyssey", "Assassins Creed Origins", "Resident Evil 7 Biohazard", "Clock Tower 3", "Far Cry 5" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(240, 40, 300, 21);

        jButton1.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        jButton1.setText("System Requirements");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 90, 240, 23);

        jButton2.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        jButton2.setText("Buy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 140, 110, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CastlevaniaLordsOfShadows.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 220, 270);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.jpg"))); // NOI18N
        jLabel1.setText("Buy");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 300);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jMenu2.setText("Orders");

        jMenuItem2.setText("History");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit Account");

        jMenuItem3.setText("Email");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Password");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Credit Card Name");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Credit Card Number");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Address");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Close");
        jMenu4.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu4MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu4MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu4MenuSelected
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MenuSelected

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
History x=new History();
x.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
   Email x=new Email();
x.setVisible(true);
this.dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
     Password x=new Password();
x.setVisible(true);
this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       CreditCardName x=new CreditCardName();
x.setVisible(true);
this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       CreditCardNumber x=new CreditCardNumber();
x.setVisible(true);
this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       Address x=new Address();
x.setVisible(true);
this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
int game=jComboBox1.getSelectedIndex();
         if(game==0)
         {
         jLabel2.setIcon(new ImageIcon("src\\CastlevaniaLordsOfShadows.png"));
         }
          if(game==1)
         {
         jLabel2.setIcon(new ImageIcon("src\\CastlevaniaMirrorOfFate.jpg"));
         }
           if(game==2)
         {
         jLabel2.setIcon(new ImageIcon("src\\CastlevaniaLordsOfShadows2.jpg"));
         }
            if(game==3)
         {
         jLabel2.setIcon(new ImageIcon("src\\ShadowOfColossus.jpg"));
         }
             if(game==4)
         {
         jLabel2.setIcon(new ImageIcon("src\\SphinxAndTheCursedMummy.png"));
         }
              if(game==5)
         {
         jLabel2.setIcon(new ImageIcon("src\\AssasienCreedOdyssey.png"));
         }
               if(game==6)
         {
         jLabel2.setIcon(new ImageIcon("src\\AssasienCreedOrigins.png"));
         }
                if(game==7)
         {
         jLabel2.setIcon(new ImageIcon("src\\ResidentEvil7.jpg"));
         }
                 if(game==8)
         {
         jLabel2.setIcon(new ImageIcon("src\\ClockTower3.jpg"));
         }
                  if(game==9)
         {
         jLabel2.setIcon(new ImageIcon("src\\FarCry5.jpg"));
         }          // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 int game=jComboBox1.getSelectedIndex();
 String a="";
        if(game==0)
         {
                   a="Castlevania Lords Of Shadows";       
         }
        if(game==1)
         {
                   a="Castlevania Mirror Of Fate";       
         }
        if(game==2)
         {
                   a="Castlevania Lords Of Shadows 2";       
         }
        if(game==3)
         {
                   a="Shadow Of Colossus";       
         }
        if(game==4)
         {
                   a="Sphinx And The Cursed Mummy";       
         }
        if(game==5)
         {
                   a="Assasien Creed Odyssey";       
         }
        if(game==6)
         {
                   a="Assasien Creed Origins";       
         }
        if(game==7)
         {
                   a="Resident Evil 7";       
         }
        if(game==8)
         {
                   a="Clock Tower 3";       
         }
        if(game==9)
         {
                   a="Far Cry 5";       
         }
        jOptionPane1.showMessageDialog(this,"Added To Cart");
               try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection x;
            String s1,s2,s3;
            s1="jdbc:mysql://localhost:3306/Game";
            s2="root";
            s3="root";
            x = DriverManager.getConnection(s1,s2,s3);
            
         String q="INSERT INTO "+Game.username+" VALUES('"+a+"');";
         Statement y;
            y=x.createStatement();
            y.executeUpdate(q);
            x.close();
            y.close();
            
        }
        catch(Exception ex)
        {}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

int game=jComboBox1.getSelectedIndex();
 
        if(game==0)
         {
                   jDialog1.setVisible (true);          
         }
        if(game==1)
         {
                  jDialog2.setVisible (true);          
         }
        if(game==2)
         {
                  jDialog3.setVisible (true);          
         }
        if(game==3)
         {
                  jDialog4.setVisible (true);         
         }
        if(game==4)
         {
                  jDialog5.setVisible (true);         
         }
        if(game==5)
         {
                   jDialog6.setVisible (true);          
         }
        if(game==6)
         {
                  jDialog7.setVisible (true);        
         }
        if(game==7)
         {
                   jDialog8.setVisible (true);         
         }
        if(game==8)
         {
                   jDialog9.setVisible (true);         
         }
        if(game==9)
         {
                   jDialog10.setVisible (true);       
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
jDialog1.setVisible (false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       jDialog2.setVisible (false);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jDialog3.setVisible (false); // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jDialog4.setVisible (false); // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       jDialog5.setVisible (false);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jDialog6.setVisible (false); // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       jDialog7.setVisible (false);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       jDialog8.setVisible (false);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       jDialog9.setVisible (false);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
       jDialog10.setVisible (false);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog10;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JDialog jDialog5;
    private javax.swing.JDialog jDialog6;
    private javax.swing.JDialog jDialog7;
    private javax.swing.JDialog jDialog8;
    private javax.swing.JDialog jDialog9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    // End of variables declaration//GEN-END:variables
}
