/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohit Vaishnav
 */import java.sql.*;
 import javax.swing.*;
public class SignUpCredit extends javax.swing.JFrame {

    /**
     * Creates new form SignUpCredit
     */
    public SignUpCredit() {
        initComponents();
        setSize(569,320);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("YouMurderer BB", 2, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 200, 160, 30);

        jLabel4.setFont(new java.awt.Font("YouMurderer BB", 2, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Card Number");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 150, 230, 40);

        jTextField2.setFont(new java.awt.Font("Lucida Calligraphy", 3, 12)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(220, 160, 320, 23);

        jTextField3.setFont(new java.awt.Font("Lucida Calligraphy", 3, 12)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(220, 210, 320, 23);

        jLabel2.setFont(new java.awt.Font("Zombie Holocaust", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("Credit card $ details");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 10, 320, 47);

        jTextField1.setFont(new java.awt.Font("Lucida Calligraphy", 3, 12)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(220, 110, 320, 23);

        jLabel5.setFont(new java.awt.Font("YouMurderer BB", 2, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Card Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 100, 190, 30);

        jButton1.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 250, 90, 23);

        jButton3.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 250, 81, 23);

        jButton2.setFont(new java.awt.Font("Castellar", 1, 12)); // NOI18N
        jButton2.setText("Give Up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(440, 20, 93, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignUpCreditCard.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String a,b,c;
        a=jTextField1.getText();
        b=jTextField2.getText();
        c=jTextField3.getText();

    
        jOptionPane1.showMessageDialog(this,"Register Successfull");
        Home z=new Home();
            z.setVisible(true);
            this.dispose();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection x;
            String s1,s2,s3;
            s1="jdbc:mysql://localhost:3306/Game";
            s2="root";
            s3="root";
            x = DriverManager.getConnection(s1,s2,s3);
            String q="INSERT INTO Account VALUES('"+Game.email+"','"+Game.username+"','"+Game.password+"','"+a+"','"+b+"','"+c+"');";
            String l="Create Table "+Game.username+" (GameName varchar(50));";
            Statement y;
            y=x.createStatement();
            y.executeUpdate(q);
            y.executeUpdate(l);
           
            
            x.close();
            y.close();
            
        }
        catch(Exception ex)
        {}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        SignUp x=new SignUp();
        x.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpCredit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
